import React from 'react';
import { api } from '../utils/api.js';
import AccountDestructionPanel from './AccountDestructionPanel.jsx';
import { clearOrgDeviceData, emergencyError } from '../lib/emergencyUi.js';
import './EmergencyProtocolPanel.css';

const base = { marginTop: 16, padding: 16, borderRadius: 12, border: '1px solid #65a30d', background: '#17230d', color: '#fff7ed' };
const field = { width: '100%', maxWidth: 520, boxSizing: 'border-box', padding: '10px 12px', borderRadius: 8, border: '1px solid rgba(255,255,255,.35)', background: 'rgba(0,0,0,.28)', color: 'inherit' };
const stageFor = (stage, lockdown, isolated) => stage === 'destroying' || stage === 'prepared' ? 4 : stage === 'isolated' || isolated ? 3 : stage === 'lockdown' || lockdown ? 2 : 0;

function Credentials({ password, setPassword, mfaCode, setMfaCode }) {
  return <div className="bf-emergency-fields"><input type="password" aria-label="Current password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Current password" style={field} /><input aria-label="Authenticator code" inputMode="numeric" autoComplete="one-time-code" value={mfaCode} onChange={(e) => setMfaCode(e.target.value)} placeholder="MFA code, if enabled" style={field} /></div>;
}

export default function EmergencyProtocolPanel({ orgId, lockdown = false, isolated = false, onChanged }) {
  const [step, setStep] = React.useState(stageFor('normal', lockdown, isolated));
  const [preview, setPreview] = React.useState(null);
  const [password, setPassword] = React.useState(''); const [mfaCode, setMfaCode] = React.useState(''); const [confirmation, setConfirmation] = React.useState('');
  const [ackReview, setAckReview] = React.useState(false); const [ackHistory, setAckHistory] = React.useState(false); const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState(''); const [statusKnown, setStatusKnown] = React.useState(false); const [permissions, setPermissions] = React.useState({ canLockdown: false, canDestroy: false });
  const finished = React.useRef(false);
  const load = React.useCallback(async ({ review = false, signal } = {}) => {
    if (!orgId || finished.current) return null;
    const result = await api(`/api/orgs/${encodeURIComponent(orgId)}/emergency/protocol${review ? '?preview=1' : ''}`, { method: 'GET', signal });
    if (finished.current || signal?.aborted) return null;
    if (result?.preview) setPreview(result.preview);
    setPermissions(result?.permissions || { canLockdown: false, canDestroy: false });
    const stage = String(result?.protocol?.stage || 'normal');
    setStep((current) => stage === 'normal' && current === 1 ? current : stageFor(stage, false, result?.protocol?.isolated)); setStatusKnown(true); return result;
  }, [orgId]);
  React.useEffect(() => { const c = new AbortController(); finished.current = false; setStatusKnown(false); setPreview(null); setPassword(''); setMfaCode(''); setConfirmation(''); setAckReview(false); setAckHistory(false); setError(''); setStep(0); load({ signal: c.signal }).catch((e) => { if (!c.signal.aborted) setError(emergencyError(e)); }); return () => c.abort(); }, [load]);
  const changed = () => Promise.resolve(onChanged?.()).catch(() => {});
  const run = async (task) => { setBusy(true); setError(''); try { await task(); } catch (e) { setError(emergencyError(e)); } finally { setBusy(false); } };
  const lock = () => run(async () => { await api(`/api/orgs/${orgId}/emergency/lockdown`, { method: 'POST', body: JSON.stringify({ enabled: true, reason: 'Emergency protocol' }) }); setStep(2); changed(); await load(); });
  const isolateOrg = () => run(async () => { await api(`/api/orgs/${orgId}/emergency/isolate`, { method: 'POST', body: JSON.stringify({ password, mfaCode }) }); setStep(3); changed(); await load({ review: true }); });
  const recover = () => run(async () => { try { await api(`/api/orgs/${orgId}/emergency/recover`, { method: 'POST', body: JSON.stringify({ password, mfaCode }) }); } catch (error) { const refreshed = await load(); if (String(refreshed?.protocol?.stage || '') !== 'normal') throw error; } setPreview(null); setConfirmation(''); setAckReview(false); setAckHistory(false); setStep(0); changed(); });
  const prepare = () => run(async () => { const result = await api(`/api/orgs/${orgId}/emergency/prepare`, { method: 'POST', body: JSON.stringify({ password, mfaCode, acknowledgeDestructionReview: true }) }); setPreview(result?.preview || preview); setStep(4); changed(); });
  const destroy = () => run(async () => { await api(`/api/orgs/${orgId}/emergency/destroy`, { method: 'POST', body: JSON.stringify({ password, mfaCode, confirmation: confirmation.trim(), acknowledgeHistoricalLimit: ackHistory }) }); finished.current = true; setPassword(''); setMfaCode(''); setConfirmation(''); try { sessionStorage.setItem('bf_account_deletion_prompt', '1'); } catch {} try { await clearOrgDeviceData(orgId); } catch {} window.location.assign('#/orgs'); });
  const style = step >= 4 ? { ...base, borderColor: '#ff2727', background: '#480000', boxShadow: '0 0 0 3px rgba(255,39,39,.22)' } : step === 3 ? { ...base, borderColor: '#ff6b24', background: '#421005' } : step === 2 ? { ...base, borderColor: '#eab308', background: '#352b03' } : step === 1 ? { ...base, borderColor: '#a3e635', background: '#20300d' } : base;
  return <section className={`bf-emergency-protocol bf-emergency-stage-${step}`} style={style} aria-labelledby="emergency-protocol-title">
    <h3 id="emergency-protocol-title">Emergency protocol</h3>
    {step === 0 && <><p>Fast, deliberate path: lock writes, restrict access to owners, review the deletion scope, then make one final exact-name confirmation.</p><button disabled={!statusKnown || !permissions.canLockdown} onClick={() => setStep(1)}>Start emergency protocol</button>{statusKnown && !permissions.canLockdown && <p>An administrator or owner must enable lockdown.</p>}</>}
    {step === 1 && <><h4>1 of 4 · Lock organization</h4><p>Freeze organization writes. Nothing is deleted and normal operation can still be restored immediately.</p><div className="bf-emergency-actions"><button disabled={busy} onClick={lock}>{busy ? 'Locking down…' : 'Enable recoverable lockdown'}</button><button disabled={busy} onClick={() => setStep(0)}>Cancel</button></div></>}
    {step === 2 && <><h4>2 of 4 · Restrict to owners</h4><p>All data remains. Confirm your identity once to make the organization owner-only. These credentials stay on this screen for the final confirmation.</p><Credentials {...{ password, setPassword, mfaCode, setMfaCode }} /><div className="bf-emergency-actions"><button disabled={busy || !password || !permissions.canDestroy} onClick={isolateOrg}>{busy ? 'Restricting…' : 'Continue to owner-only access'}</button></div></>}
    {step === 3 && <><h4>3 of 4 · Review full deletion</h4><p>The organization is frozen and non-owner access is denied. Nothing has been deleted.</p>{preview && <div className="bf-emergency-scope"><div><strong>Organization</strong><span>{preview.org?.name || orgId}</span></div><div><strong>Members</strong><span>{preview.memberCount ?? 0}</span></div><div><strong>Database rows</strong><span>{preview.totalRows ?? 0}</span></div><div><strong>Drive objects</strong><span>{preview.driveObjectCount ?? 0}</span></div><div><strong>Key records</strong><span>{preview.keyMaterialRows ?? 0}</span></div></div>}<label className="bf-emergency-ack"><input type="checkbox" checked={ackReview} onChange={(e) => setAckReview(e.target.checked)} /><span>I reviewed the deletion scope. The next step only arms final confirmation; it does not delete data.</span></label><div className="bf-emergency-actions"><button disabled={busy || !password} onClick={recover}>Recover organization</button><button disabled={busy || !preview || !ackReview} onClick={prepare}>{busy ? 'Arming…' : 'Continue to final confirmation'}</button></div></>}
    {step === 4 && <><h4>4 of 4 · Irreversible deletion</h4><p className="bf-emergency-final-warning">This is the last step. Once you continue, Bondfire deletes the organization’s active data and server-held recovery material. There is no restore action.</p><p>Type <code>{preview?.confirmationPhrase || 'DESTROY …'}</code> exactly.</p><input aria-label="Deletion confirmation phrase" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} placeholder={preview?.confirmationPhrase || 'Confirmation phrase'} style={field} /><Credentials {...{ password, setPassword, mfaCode, setMfaCode }} /><label className="bf-emergency-ack"><input type="checkbox" checked={ackHistory} onChange={(e) => setAckHistory(e.target.checked)} /><span>I understand provider-managed historical backups and copies downloaded to other devices cannot be recalled by this action.</span></label><div className="bf-emergency-actions"><button disabled={busy || !password} onClick={recover}>Recover organization instead</button><button disabled={busy || !statusKnown || !preview?.confirmationPhrase || !password || !ackHistory || confirmation.trim() !== preview?.confirmationPhrase} onClick={destroy}>{busy ? 'Destroying…' : 'Destroy organization permanently'}</button></div></>}
    {step === 5 && <><h4>Organization deleted</h4><p>The organization’s active data and server-held recovery material have been removed. Your personal account still exists.</p><a href="#/orgs">Return to your organizations</a><AccountDestructionPanel /></>}
    {!statusKnown && !finished.current && <p role="status">Protocol status must load before actions are available.</p>}{error && !finished.current && <button disabled={busy} onClick={() => { setError(''); load({ review: step >= 3 }).catch((e) => setError(emergencyError(e))); }}>Refresh protocol status</button>}{error && <div role="alert" className="bf-emergency-error">{error}</div>}
  </section>;
}
